"""
audit.py — Audit log data model.

The AuditLog schema is intentionally DynamoDB-compatible:
  - `log_id`   → partition key (String)
  - `timestamp` → ISO-8601 string sort key
  - All fields are simple scalars or short strings.

To persist to DynamoDB, swap the in-memory list in audit_service.py
for a boto3 put_item call using this model's `.to_dynamo()` method.
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import Optional
from datetime import datetime, timezone
import uuid


class AuditLog(BaseModel):
    """A single auditable query event."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "log_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                "timestamp": "2024-01-01T12:00:00.123456+00:00",
                "user_id": "user-123",
                "natural_language_query": "Show me total sales by region for last quarter",
                "generated_sql": "SELECT region, SUM(amount) AS total FROM sales GROUP BY region",
                "status": "success",
                "execution_time_ms": 142.7,
                "row_count": 4,
                "environment": "development",
                "error": None,
            }
        }
    )

    log_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this audit entry (DynamoDB partition key)",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO-8601 UTC timestamp (DynamoDB sort key)",
    )
    user_id: str = Field(..., description="The requesting user")
    natural_language_query: str = Field(..., description="The original NL question")
    generated_sql: str = Field(..., description="The SQL generated by the LLM")
    status: str = Field(..., description="'success' | 'rejected' | 'error'")
    execution_time_ms: float = Field(
        0.0, description="Total wall-clock time for the request in milliseconds"
    )
    row_count: int = Field(0, description="Number of rows returned by the SQL execution")
    environment: str = Field("", description="Runtime environment (development/production)")
    error: Optional[str] = Field(None, description="Error message if status != 'success'")

    def to_dynamo(self) -> dict:
        """
        Serialize this entry to the DynamoDB Item format.

        Usage:
            table.put_item(Item=log.to_dynamo())
        """
        item = self.model_dump()
        # DynamoDB doesn't accept None — strip null fields
        return {k: v for k, v in item.items() if v is not None}
