"""
copilot_controller.py — Copilot-level endpoints.

Provides endpoints that support the chat flow beyond the core query pipeline:
    GET /api/v1/copilot/next-steps  — LLM-generated follow-up questions
"""

import logging
from fastapi import APIRouter, HTTPException, Query, status

from app.services.next_steps_service import generate_next_steps
from app.services.memory_service import get_user_memory
from app.models.insight import InsightReport

logger = logging.getLogger(__name__)
router = APIRouter(tags=["Copilot"])

_DEMO_USER = "nicole.goncalves@acme.com"


class NextStepsResponse:
    pass


from pydantic import BaseModel
from typing import List


class NextStepsResponse(BaseModel):
    next_steps: List[str]


@router.get(
    "/copilot/next-steps",
    response_model=NextStepsResponse,
    summary="Get LLM-generated follow-up question suggestions",
)
async def get_next_steps(
    execution_id: str = Query(..., description="The query_id from the last QueryResponse"),
    user_id: str = Query(default=_DEMO_USER, description="The requesting user"),
) -> NextStepsResponse:
    """
    Return 3 follow-up question suggestions generated by watsonx.ai.

    Reads the last interaction from the user's memory to retrieve
    the original question and builds an LLM prompt with the result summary.

    Falls back to rule-based suggestions when WATSONX_MOCK=True or on error.

    - **execution_id**: the `query_id` from the last `QueryResponse`
    - **user_id**: the requesting user (defaults to demo user)
    """
    memory = get_user_memory(user_id)
    if not memory or not memory.interactions:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No interaction history found for user '{user_id}'.",
        )

    last = memory.interactions[-1]

    # Build a minimal InsightReport stub for the prompt
    # (real insights are not re-stored in memory, only the query/sql)
    stub_insights = InsightReport(
        row_count=last.row_count,
        columns_analyzed=[],
        key_insights=[],
        trends=[],
        anomalies=[],
        summary=f"{last.row_count} row(s) returned. Status: {last.status}.",
    )

    suggestions = await generate_next_steps(
        question=last.query,
        insights=stub_insights,
        rows_sample=[],
    )

    logger.info(
        "Next steps served",
        extra={"user_id": user_id, "execution_id": execution_id, "count": len(suggestions)},
    )

    return NextStepsResponse(next_steps=suggestions)
