import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { delay, map, of, Observable } from 'rxjs';
import { SqlPreview, CostEstimate, SqlValidation } from '../models/copilot.models';
import { CopilotStateService } from './copilot-state.service';

// ─────────────────────────────────────────────────────────────
// SqlService
//
// generate()     → reads SQL from CopilotStateService cache
//                  (SQL was already generated by POST /query)
// validate()     → POST /api/sql/validate
// estimateCost() → POST /api/cost/estimate
// override()     → stays mock (no override endpoint)
// ─────────────────────────────────────────────────────────────

const API = '/api';

@Injectable({ providedIn: 'root' })
export class SqlService {
  private http  = inject(HttpClient);
  private state = inject(CopilotStateService);

  // ── Reads SQL from cached BackendQueryResponse ───────────
  // SQL is generated inside the POST /query pipeline call.
  // We assemble a SqlPreview from the cached result + cost.
  // --------------------------------------------------------
  generate(question: string): Observable<SqlPreview> {
    const cached = this.state.lastResponse();
    if (cached?.result) {
      const cost = cached.cost_estimate;
      const preview: SqlPreview = {
        sql:         cached.result.sql,
        sessionId:   cached.query_id,
        generatedAt: new Date(cached.timestamp).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
        table:       cached.result.data.columns[0] ?? 'unknown',
        validation:  { safe: true, warnings: [] },
        cost: {
          bytesScanned:  cost ? `~${(cost.bytes_scanned / 1e9).toFixed(1)} GB` : '—',
          estimatedCost: cost ? `$${cost.estimated_cost_usd.toFixed(4)}` : '—',
          table:         'mock-sqlite',
          engine:        'aws',
        },
      };
      return of(preview);
    }
    // ── MOCK fallback ────────────────────────────────────────
    return of(MOCK_SQL_PREVIEW).pipe(delay(900));
  }

  // ── POST /api/sql/validate ───────────────────────────────
  // Maps backend { valid, reason } to frontend { safe, warnings }
  // --------------------------------------------------------
  validate(sql: string): Observable<SqlValidation> {
    return this.http.post<{ valid: boolean; reason: string }>(`${API}/sql/validate`, { sql }).pipe(
      map(r => ({ safe: r.valid, warnings: r.valid ? [] : [r.reason] })),
    );
    // ── MOCK (fallback) ─────────────────────────────────────
    // return of({ safe: true, warnings: [] }).pipe(delay(300));
  }

  // ── POST /api/cost/estimate ──────────────────────────────
  // Maps backend CostEstimate to frontend CostEstimate shape
  // --------------------------------------------------------
  estimateCost(sql: string): Observable<CostEstimate> {
    return this.http.post<{
      bytes_scanned:      number;
      estimated_cost_usd: number;
      table_count:        number;
      has_filter:         boolean;
    }>(`${API}/cost/estimate`, { sql }).pipe(
      map(r => ({
        bytesScanned:  `~${(r.bytes_scanned / 1e9).toFixed(1)} GB`,
        estimatedCost: `$${r.estimated_cost_usd.toFixed(4)}`,
        table:         `${r.table_count} table(s)`,
        engine:        'aws' as const,
      })),
    );
    // ── MOCK (fallback) ─────────────────────────────────────
    // return of(MOCK_COST).pipe(delay(500));
  }

  // ── stays mock — no override endpoint on the backend ─────
  override(sessionId: string, sql: string): Observable<SqlPreview> {
    return of({ ...MOCK_SQL_PREVIEW, sql }).pipe(delay(300));
  }
}

// ─────────────────────────────────────────────────────────────
//  MOCK DATA — kept as reference / fallback
// ─────────────────────────────────────────────────────────────

const MOCK_COST: CostEstimate = {
  bytesScanned:  '~4.7 GB',
  estimatedCost: '$0.023',
  table:         'acme-prod.sales.transactions',
  engine:        'aws',
};

export const MOCK_SQL_PREVIEW: SqlPreview = {
  sessionId:   'sess_9f3a',
  generatedAt: '09:15:22',
  table:       'acme-prod.sales.transactions',
  validation:  { safe: true, warnings: [] },
  explanation: 'The query filters 2024 transactions for Q2 and Q3, calculates total revenue per product in each period, and returns the 50 products with the largest percentage revenue drop between Q2 and Q3 (drops greater than 20% only).',
  cost:        MOCK_COST,
  sql: `WITH quarterly_sales AS (
  SELECT
    product_id,
    product_name,
    SUM(CASE WHEN quarter = 'Q2' THEN revenue END) AS q2_revenue,
    SUM(CASE WHEN quarter = 'Q3' THEN revenue END) AS q3_revenue
  FROM \`acme-prod.sales.transactions\`
  WHERE year = 2024
    AND quarter IN ('Q2', 'Q3')
  GROUP BY 1, 2
)
SELECT
  product_name,
  q2_revenue,
  q3_revenue,
  ROUND((q3_revenue - q2_revenue) / q2_revenue * 100, 2) AS pct_change
FROM quarterly_sales
WHERE (q3_revenue - q2_revenue) / q2_revenue * 100 < -20
ORDER BY pct_change ASC
LIMIT 50;`,
};
